# Generated by Django 4.2 on 2024-09-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=200),
        ),
    ]
